[package]
name = "sep2-bridge"
version.workspace = true
edition.workspace = true

[dependencies]
async-broadcast.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
derive_more = { workspace = true, features = ["display"] }
env_logger.workspace = true
exponential-backoff.workspace = true
git-version.workspace = true
log.workspace = true
num-traits.workspace = true
rand.workspace = true
sep2_client = { workspace = true, features = ["all"] }
sep2_common = { workspace = true, features = ["all"] }
sunspec = { workspace = true, default-features = false, features = ["tokio-modbus", "model1", "model103", "model701", "model702", "model703", "model704", "model709", "model710", "model711", "model713"] }
tokio = { workspace = true, features = ["full"] }
tokio-modbus.workspace = true
url.workspace = true

[dev-dependencies]
proptest.workspace = true
wiremock.workspace = true
regex.workspace = true
tokio-modbus = { workspace = true, features = ["tcp-server"] }
